### PR TITLE
WIP - Vite migration

### PR DESCRIPTION
**Pull request by dvkam**
**DO NOT MERGE YET**

I migrated the App to Vite.

However I noticed some odd behaviour in both versions (CRA and Vite) - when I try to submit a tx with Temple the operation is never even added to the mempool (I think) - so it triggers the timeout every time. However when I switch to Kukai it works. Other people experience a similar behaviour in other situations: https://github.com/ecadlabs/taquito/issues/1690

   - removed unused dependencies due to the migration and updated to current versions e.g. taquito to v17
   - removed unused files now that were related to CRA and replaced with needed Vite files e.g. Vite config
   - in Vite its import.meta.env.VITE_ instead of process.env.
   - Also I added eslint so it highlights possible wrong patterns. The app still works, so fixing issues that are highlighted could be done as another PR after this - I started with some small changes but stopped as this would be better as another PR, I can revert these changes if thats desired.
   - the postinstall might be not needed anymore, its currently not included

What needs to be done:
-  **The app needs to be tested with Android studio to see if it also works on Android like before.** 
- make changes in the README so it reflects the updated code

Will finish this asap.

### CODE REVIEW

**Comment by zamrokk** [comment]
This is weird, I never noticed this and I have done this training quite a
lot

Do you have a complete scenario yo reproduce it?

**Comment by dvkam** [comment]
> This is weird, I never noticed this and I have done this training quite a lot Do you have a complete scenario yo reproduce it? 

Interesting, I tested it with Temple in different browsers and on two different machines and with different rpc.
The flow is:

- start the app (either CRA or Vite version)
- connect Temple wallet
- start a new game
- I play and chose either rock, paper or scissor
- I confirm the tx in Temple
- Waiting for operation to get confirmed but it never happens and I get the timeout. By looking at tzkt it never even gets added to the mempool

When I try with Kukai it works perfectly fine.

**Comment by zamrokk** [comment]
and with other wallet like airgap or trustwallet ?

**Comment by dvkam** [comment]
I will test it with other wallets later and let you know

**Comment by zamrokk** [comment]
hum , With temple, I confirm, nothing happen ...

**Comment by zamrokk** [comment]
there is actually an issue with Temple 1.16.3 , I will report that to their team

**Comment by zamrokk** [comment]
I posted it on MadFish Telegram, it can be only the Temple extension, I can't see other parts failing

Thanks, dude !

**Comment by zamrokk** [comment]
They released a new version but for me it does not fix the issue they have

I need to try to play with Android first before merging the PR

**Comment by zamrokk** [comment]
ok, the app works on my Android phone  =)

**Pull request merged**
